// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADpF9fb4sKtcIItzl9RDhkbzPsUq0rqm4',
    appId: '1:406213593729:web:ab4dbd9809a165a8351b80',
    messagingSenderId: '406213593729',
    projectId: 'food-app-67386',
    authDomain: 'food-app-67386.firebaseapp.com',
    storageBucket: 'food-app-67386.appspot.com',
    measurementId: 'G-1PK4SPNPSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQYVjmL3dgwg_odUhsu2HPfubVa9UT6rk',
    appId: '1:406213593729:android:56e1dec8c5b93755351b80',
    messagingSenderId: '406213593729',
    projectId: 'food-app-67386',
    storageBucket: 'food-app-67386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdd2iSSiQrN1ZV_89AgxEaaiFhWdqfi1M',
    appId: '1:406213593729:ios:724460693d8982fb351b80',
    messagingSenderId: '406213593729',
    projectId: 'food-app-67386',
    storageBucket: 'food-app-67386.appspot.com',
    iosClientId:
        '406213593729-428o1ied56ca55oeqctulogaep41lnku.apps.googleusercontent.com',
    iosBundleId: 'com.example.devApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdd2iSSiQrN1ZV_89AgxEaaiFhWdqfi1M',
    appId: '1:406213593729:ios:802fa958fcc8a371351b80',
    messagingSenderId: '406213593729',
    projectId: 'food-app-67386',
    storageBucket: 'food-app-67386.appspot.com',
    iosClientId:
        '406213593729-h5qkslcgughdbsrv4hvdduq5k7u4rhth.apps.googleusercontent.com',
    iosBundleId: 'com.example.devApp.RunnerTests',
  );
}
